spring:
  datasource:
    url: jdbc:h2:mem:credit-request-service-db
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

